<a href="https://colab.research.google.com/github/viratbhoomi/DSA/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
# arrays are not native data struvtures in python. Instead, we use list, which are similar but more flexible. However, there are models available in python
# for creating more efficient arrays with a specific data type, mainly for numeric data  type.
# We can use numpy module and array module to create an array data structure in python.
# These modules  provide an array data structure that is more memory efficient than the list for specific data structures.
# They store elements as contiguous block of memory without pointers,
# reducing memory overhead. However array objects can only store elements of same data type.
# Types of array - one dimensional and multi dimensional(two, three, four,-------n dimensional).

arr = [[11,68,87,12],[5,4,10,11,8]]
# to access the elements of the array we need to use row index and column index numbers
# accessing 87 and 11 elements from the array
print(arr[0][2])
print(arr[1][3])

# two, three, four---- n dimensional array in the memory will be represented as one dimensional array.


87
11


In [7]:
# prompt:

# creating a two dimensional array
arr = [[11,68,87,12],[5,4,10,11,8]]

# accessing the elements of the array using row index and column index numbers
print(arr[0][2])  # accessing 87
print(arr[1][3])  # accessing 11

# creating a three dimensional array
arr3d = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

# accessing the elements of the three dimensional array using row index, column index and depth index numbers
print(arr3d[0][1][2])  # accessing 6
print(arr3d[1][0][1])  # accessing 8


87
11
6
8


In [14]:
# creating an array
import array
# this will create a memory block for an array in the memory the memory size will be changed based on the elements.
# array is a standard library in python it is more memory efficient than lists in python.
# the only limitation in the array is it supports only basic data types, custom data types or mixed data types are not allowed.
arr = array.array('i')
print(arr)

arr_1 = array.array('i',[1,2,3,4])
print(arr_1)

import numpy as np
np_array = np.array([],dtype=int)
print(np_array)
np_array_1 = np.array([1,2,3,4,5,6])
print(np_array_1)

# creating an empty array by using array and numpy the time complexity and space complexity is O(1)
# creating the array with elements in both array and numpy module is O(N)



array('i')
array('i', [1, 2, 3, 4])
[]
[1 2 3 4 5 6]


In [4]:
# Note : Python does not have built-in support for Arrays, but Python Lists can be used instead.
# Inserting Elements to array
# inserting elements in the array is in 3 ways inserting in the starting,middle and last.
# inserting the elements in the start and middle is time consuming process. so inserting them in the last is the efficient process.
import array
arr_1 = array.array('i',[1,2,3,4])
print(arr_1)
# time complexity for inserting depends on the no of elements that are shifted to right in the array.
# in the worst case scenario if the elements are inserted at the biginning of the array the time complexity is O(N)
# the space complexity is O(1), inserting element is constant.
arr_1.insert(4,6)
print(arr_1)

# traversing the array
from array import *
arr_1 = array('i',[1,2,4,5,7,8])
arr_2 = array('d',[6.5,5.8,4.4,8.9,9.1,7.3])

def traversing_array(array):
  print("Traversing the array: ")
  for i in array: # ---------------O(N)
    print(i) # -------O(1)
  print("The Time and Space Complexity for Traversing the array is O(N) & O(1) ")
traversing_array(arr_1)


array('i', [1, 2, 3, 4])
array('i', [1, 2, 3, 4, 6])
Traversing the array: 
1
2
4
5
7
8
The Time and Space Complexity for Traversing the array is O(N) & O(1) 


In [10]:
# Accessing an element of array
from array import *

arr = array('i',[1,2,3,4,5])
def accessElement(array,index):
  if index >= len(array):  # -------------------O(1)
    print("No element present with this index")   # ------------------------O(1)
  else:
    print(array[index]) # -------------------O(1)

  print("The Time and Space Complexity for accessing an element of array O(1) ")
accessElement(arr,5)


No element present with this index
The Time and Space Complexity for accessing an element of array O(1) 


In [14]:
# searching for an element in an array
# searching an element in an array is by using "linear search algorithm".
# The time complexity for range and len() is O(1)

from array import *

arr = array('i',[1,2,3,4,5])
def linearSearch(array,target):
  print("The Time and Space Complexity for searching for an element in an array is O(N) & O(1) ")
  for i in range(len(array)): # ---------------O(N)
    if array[i] == target: # ------------O(1)
      return i  # ------------O(1)
  return -1  # ------------O(1)
linearSearch(arr,5)







The Time and Space Complexity for searching for an element in an array is O(N) & O(1) 


4

In [18]:
# deleting an element from array
# deletion is very efficient when we remove the last element otherwise deletion becomes time consuming.

from array import *

arr = array('i',[1,2,3,4,5])
arr.remove(5)
print(arr)

# time and space complexity for removing the element in an array in worst case scenario is O(N)
# if we remove the last element then O(1) & space complexity O(1)




array('i', [1, 2, 3, 4])


In [1]:
# Time and Space Complexity for One Dimensional Array
# creating an empty array           O(1)   O(1)
# creating an array with elements   O(N)   O(N)
# inserting a value in an array     O(N)   O(1)
# traversing a given array          O(N)   O(1)
# accessing a given value           O(1)   O(1)
# searching a given value           O(N)   O(1)
# deleting a given value            O(N)   O(1)






In [19]:
from array import *

# create an array and traverse
arr = array('i',[1,2,3,4,5])
for i in arr:  #----------------O(N)
  print(i)

# Access individual elements through indexes
print(arr[0])
print(arr[3])

# append any value to the array using append() method.
arr.append(6)   #------------O(1)
print(arr)

# insert a value in an array using insert() method
arr.insert(3,11)
print(arr)

# extend python array using extend() method.
new_arr = array('i',[8,9,7,8,5])
arr.extend(new_arr)
print(arr)

# add items from list into array using fromlist() method.
l = [9,7,5,8,7]
arr.fromlist(l)
print(arr)


# remove any element using reverse() method.
arr.remove(11)
print(arr)


# remove last array element using pop().
arr.pop()
print(arr)

# fetch any element through its index using index() method.
print(arr.index(4))

# reverse a python array using reverse() method.
arr.reverse()
print(arr)

# get array buffer information through buffer_info() method.
print(arr.buffer_info())

# check for number of occurences of an element using count().
print(arr.count(8))

# convert array to string using tostring() method. (removed from python)
# array_to_string = arr.tostring()
# print(array_to_string)


# convert array to python list using tolist() method.
array_to_list = arr.tolist()
print(array_to_list)

# slice elements from an array
print(arr[0:3])



1
2
3
4
5
1
4
array('i', [1, 2, 3, 4, 5, 6])
array('i', [1, 2, 3, 11, 4, 5, 6])
array('i', [1, 2, 3, 11, 4, 5, 6, 8, 9, 7, 8, 5])
array('i', [1, 2, 3, 11, 4, 5, 6, 8, 9, 7, 8, 5, 9, 7, 5, 8, 7])
array('i', [1, 2, 3, 4, 5, 6, 8, 9, 7, 8, 5, 9, 7, 5, 8, 7])
array('i', [1, 2, 3, 4, 5, 6, 8, 9, 7, 8, 5, 9, 7, 5, 8])
3
array('i', [8, 5, 7, 9, 5, 8, 7, 9, 8, 6, 5, 4, 3, 2, 1])
(137293598355424, 15)
3
[8, 5, 7, 9, 5, 8, 7, 9, 8, 6, 5, 4, 3, 2, 1]
array('i', [8, 5, 7])


In [31]:
# Two Dimensional Array
# time complexity for creating a two dimensional array is O(mn).

import numpy as np
arr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(arr)

# insertion in 2d array
# time complexity is O(mn) for adding the row or column in the start.
# row -- axis=0, column -- axis=1
# 0 - which the position of the matrix. we can change the position based on the requirement like 0,1,2,3---
new_two_dim_arr = np.insert(arr,0,[[1,2,3,4]], axis=1)
print(new_two_dim_arr)

# we can also add the new row at the end of the matrix directly by using the append().
new_dim_arr = np.append(arr,[[1,2,3,4]],axis=0)
print(new_dim_arr)





[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


In [32]:
# accessing the elements of two dimensional array.
# time complexity is O(1) and space complexity O(1)

import numpy as np
arr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(arr)

def accessElements(array, rowIndex, columnIndex):
  if rowIndex >= len(array) and columnIndex >= len(array[0]):   #---------------O(1)
    print("Incorrect Index")   #------------------------O(1)
  else:
    print(array[rowIndex][columnIndex])  #---------------O(1)
accessElements(arr, 3, 3)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
9


In [35]:
# traversing the two dimensional array
import numpy as np
arr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(arr)

def traversingTwoDimArray(array):
  for i in range(len(array)):   #------------------O(mn)
    for j in range(len(array[0])):   #------------------O(n)
      print(array[i][j],  end=" ")   #------------------O(1)
traversingTwoDimArray(arr)
# time complexity and space complexity is O(n^2) & O(1)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
11 15 10 6 10 14 11 5 12 17 12 8 15 18 14 9 

In [36]:
# searching two dimensional array
# there are multiple algorithms for searching in two dimensional array. Here we are using linear search algorithm.

import numpy as np
arr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(arr)

def searchTwoDimensionalArray(array,value):
  for i in range(len(array)):  # ----------------------O(mn)
    for j  in range(len(array[0])):  # ----------------O(n)
      if array[i][j]==value: # ------------------------O(1)
        return "The value is located at index "+str(i)+" "+str(j)
  return "The element is not found"
searchTwoDimensionalArray(arr,14)

# time complexity and space complexity O(mn) & O(1)
# in the above function we have same no of rows and columns so the time time complexity is O(mn) otherwise it is quadratic time complexity.



[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


'The value is located at index 1 1'

In [37]:
# Deletion Two Dimensional Array
# the time complexity for deleting row or column is O(mn) becoz after deleting it needs to copy the remaining elemnts without loosing
# and the space complexity is also the same O(mn).

import numpy as np
arr = np.array([[11,15,10,6],[10,14,11,5],[12,17,12,8],[15,18,14,9]])
print(arr)

new_arr = np.delete(arr,0,axis=0)
print(new_arr)


[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
[[10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [38]:
# time and space complexity of 2D array
# creating an empty array           O(1)    O(1)
# creating an array with elements   O(mn)   O(mn)
# inserting a value in an array     O(mn)   O(mn)
# traversing a given array          O(mn)   O(1)
# accessing a given value           O(1)    O(1)
# searching a given value           O(mn)   O(1)
# deleting a given value            O(mn)   O(mn)

In [ ]:
# when to use or avoid arrays
# use
# to store multiple values of same data type.
# when we want to access random values
# avoid
# same data type elements
# reserve specific amount of memory
